query FooterBlock {
    FooterBlock {
        items {
            ContentAreaGeneral {
                __typename
                ... on FooterLinksGeneralBlock {
                    LinkListHeader
                    LinkList {
                        text
                        title
                        url {
                            default
                        }
                    }
                    TextField
                }
            }
            ContentAreaForSocials {
                __typename
                ... on FooterSocials {
                    Icon {
                        url {
                            default
                        }
                    }
                    Link {
                        default
                    }
                    Title
                }
            }
        }
    }
}
