query FooterBlock {
    FooterBlock {
        items {
            SocialsHeader
            ContentAreaGeneral {
                __typename
                ... on FooterLinksGeneralBlock {
                    LinkListHeader
                    LinkList {
                        text
                        title
                        url {
                            default
                        }
                    }
                    TextField
                }
                ... on FooterTextGeneralBlock {
                    TextListHeader
                    ContentAreaForTextRows {
                        __typename
                        ... on TextRow {
                            TextRow
                        }
                    }
                }
            }
            ContentAreaForSocials {
                __typename
                ... on FooterSocials {
                    Icon {
                        url {
                            default
                        }
                    }
                    Link {
                        default
                    }
                    Title
                }
            }
        }
    }
}
