query OmOss {
    CommonPage(where: { _metadata: { url: { default: { eq: "/en/om-oss/" } } } }) {
        items {
            HeaderProp
            PreambleProp
            ImageProp {
                url {
                    default
                }
            }
            ContentAreaProp {
                __typename
                ... on SectionBlock {
                    ContentAreaProp {
                        __typename
                        ... on CommonPage {
                            ...SitePagePartialFields
                        }
                        __typename
                        ... on TextImageBlock {
                            TextBlock {
                                TextProp {
                                    html
                                }
                            }
                            ImageBlock {
                                ImageProp {
                                    url {
                                        default
                                    }
                                }
                            }
                            PlaceImageRight
                        }
                    }
                }
            }
        }
    }
}
