query StartPage {
    StartPage {
        items {
            PageHeader {
                Image {
                    url {
                        default
                    }
                }
                Header
                Preamble
                CTALink {
                    text
                    url {
                        default
                    }
                }
            }
            ContentAreaProp {
                __typename
                ... on SectionBlock {
                    ContentAreaProp {
                        __typename
                        ... on TextImageBlock {
                            HeadingProp
                            TextBlock {
                                TextProp {
                                    html
                                }
                            }
                            ImageBlock {
                                HeadingProp
                                ImageProp {
                                    url {
                                        default
                                    }
                                }
                            }
                            PlaceImageRight
                        }
                    }
                }
                ... on TextBlock {
                    TextProp {
                        html
                    }
                }
            }
        }
    }
}
