query StartPageQuery {
    StartPage {
        items {
            TextProp {
                html
            }
            HeaderBlock {
                Preamble
                ImageBlock {
                    HeadingProp
                    ImageProp {
                        url {
                            default
                        }
                    }
                }
            }
            ContentAreaProp {
                __typename
                ... on SectionBlock {
                    HeadingProp
                    ContentAreaProp {
                        __typename
                        ... on TextImageBlock {
                            HeadingProp
                            TextBlock {
                                TextProp {
                                    html
                                }
                            }
                            ImageBlock {
                                HeadingProp
                                ImageProp {
                                    url {
                                        default
                                    }
                                }
                            }
                            PlaceImageRight
                        }
                    }
                }
                ... on TextBlock {
                    TextProp {
                        html
                    }
                }
            }
            FooterBlock {
                ContactHeading
                Email
                Phone
                Address
                Links {
                    text
                    title
                    target
                    url {
                        default
                    }
                }
            }
        }
    }
}